version: '2'
services:
  uibuilder7.2:
    build:
      context: ../../
      dockerfile: make/dev/container/uibuilder/Dockerfile.arm64v8
    image: 10.111.25.119/board/dev_uibuilder:7.2
    volumes:
      - ../../src/ui:/board_src
    environment:
      MODE: build
    entrypoint:
      - /entrypoint.sh
