apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "board.apiserver.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
  name: {{ include "board.apiserver.fullname" . }}-kubeconfig
data:
  kubeconfig: |-
{{ .Files.Get "files/apiserver/kubeconfig" | indent 4 }}
