apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "board.db.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
  name: {{ include "board.db.fullname" . }}-config
data:
  {{- $files := .Files }}
  {{- range tuple "files/db/my.cnf" }}
  {{ base . }}: |-
{{ $files.Get . | trim | indent 4}}
  {{- end }}
