apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "board.elasticsearch.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
  name: {{ include "board.elasticsearch.fullname" . }}-env
data:
{{- range $line := .Files.Lines "files/elasticsearch/env" }}
{{ $trim := trim $line }}
{{- if $trim -}}
{{ regexReplaceAll "^([A-Za-z0-9._%+-]+)=(.*)$" $trim "$1: \"$2\"" | indent 2}}
{{- end -}}
{{- end }}