apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "board.elasticsearch.fullname" . }}
  labels:
    app: {{ include "board.elasticsearch.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
spec:
  replicas: {{.Values.elasticsearch.replicaCount}}
  selector:
    matchLabels:
      app: {{ include "board.elasticsearch.name" . }}
      instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "board.elasticsearch.name" . }}
        instance: {{ .Release.Name }}
    spec:
      initContainers:
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
      - name: "sysctl"
        image: {{ include "board.elasticsearch.image.image" . }}
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - envFrom:
        - configMapRef:
            name: {{ include "board.elasticsearch.fullname" . }}-env
        image: {{ include "board.elasticsearch.image.image" . }}
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        name: elasticsearch
        command:
        - /bin/sh
        - -cxe
        - |
          ulimit -l unlimited
          ulimit -m unlimited
          ulimit -n 65536
          ulimit -u 65536
          ulimit -f unlimited
          ulimit -v unlimited
          /entrypoint.sh
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        securityContext:
          privileged: true
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      initContainers:
      - command:
        - /sbin/sysctl
        - -w
        - vm.max_map_count=262144
        image: {{ include "board.elasticsearch.image.image" . }}
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
      volumes:
      - hostPath:
          path: '{{.Values.localtime.path}}'
        name: localtime
      - name: data
      {{- if .Values.elasticsearch.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.elasticsearch.persistence.existingClaim | default (include "board.elasticsearch.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      restartPolicy: '{{.Values.elasticsearch.restartPolicy}}'
      schedulerName: default-scheduler
    {{- with .Values.elasticsearch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.elasticsearch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.elasticsearch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
