apiVersion: v1
kind: Service
metadata:
  name:  elasticsearch  # board kibana hardcodes elasticsearch name to 'elasticsearch', so here is service name elasticsearch.
  labels:
    app: {{ include "board.elasticsearch.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
  - port: {{ .Values.elasticsearch.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "board.elasticsearch.fullname" . }}
    instance: {{ .Release.Name }}
