apiVersion: v1
kind: Service
metadata:
  name:  grafana  # board proxy hardcodes grafana name to 'grafana', so here is service name grafana.
  labels:
    app: {{ include "board.grafana.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
  - port: {{ .Values.grafana.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "board.grafana.fullname" . }}
    instance: {{ .Release.Name }}
