apiVersion: v1
kind: Service
metadata:
  name:  kibana  # board proxy hardcodes kibana name to 'kibana', so here is service name kibana.
  labels:
    app: {{ include "board.kibana.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
  - port: {{ .Values.kibana.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "board.kibana.fullname" . }}
    instance: {{ .Release.Name }}
