apiVersion: v1
kind: Service
metadata:
  name:  prometheus  # board grafana hardcodes prometheus name to 'prometheus', so here is service name prometheus.
  labels:
    app: {{ include "board.prometheus.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "board.prometheus.fullname" . }}
    instance: {{ .Release.Name }}
