apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "board.prometheus.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
  name: {{ include "board.prometheus.fullname" . }}
data:
  {{- $files := .Files }}
  {{- range tuple "files/prometheus/prometheus.yml" }}
  {{ base . }}: |-
{{ $files.Get . | trim | indent 4}}
  {{- end }}
