apiVersion: v1
kind: Service
metadata:
  name: {{ include "board.proxy.fullname" . }}
  labels:
    app: {{ include "board.proxy.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
  - port: {{ .Values.proxy.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  - name: https
    port: {{ .Values.proxy.service.httpsPort }}
    protocol: TCP
    targetPort: https
  - name: proxy
    port: {{ .Values.proxy.service.proxyPort }}
    protocol: TCP
    targetPort: proxy
  selector:
    app: {{ include "board.proxy.fullname" . }}
    instance: {{ .Release.Name }}
