apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "board.proxy.name" . }}
    chart: {{ include "board.chart" . }}
    instance: {{ .Release.Name }}
  name: {{ include "board.proxy.fullname" . }}
data:
  {{- $files := .Files }}
  {{- $root := . }}
  {{- range tuple "files/proxy/nginx.conf" }}
  {{ base . }}: |-
{{ $files.Get . | trim | replace "127.0.0.11" "kube-dns.kube-system.svc.cluster.local" | replace "http://apiserver:" (printf "http://apiserver.%s.svc.cluster.local:" $root.Release.Namespace) | replace "http://grafana:" (printf "http://grafana.%s.svc.cluster.local:" $root.Release.Namespace) | replace "http://kibana:" (printf "http://kibana.%s.svc.cluster.local:" $root.Release.Namespace) | indent 4}}
  {{- end }}
