FROM {{.Base}}
{{if .Author}}MAINTAINER {{.Author}}
{{end -}}
{{if .EnvList}}{{range .EnvList}}ENV {{.EnvName}} {{.EnvValue}}
{{end}}{{end -}}
{{if .Volume}}{{range .Volume}}VOLUME [ {{str2exec .}} ]
{{end}}{{end -}}
{{if .Copy}}{{range .Copy}}COPY [ "{{.CopyFrom}}", {{str2exec .CopyTo}} ]
{{end}}{{end -}}
{{if .RUN}}{{range .RUN}}RUN {{.}}
{{end}}{{end -}}
{{if .ExposePort}}{{range .ExposePort}}EXPOSE {{.}}
{{end}}{{end -}}
{{if .EntryPoint}}ENTRYPOINT [ {{str2exec .EntryPoint}} ]
{{end -}}
{{if .Command}}CMD [ {{str2exec .Command}} ]
{{end -}}
