// @APIVersion 1.1.0
// @Title Board API Refactor
// @Description Refactor and update current version of Board API.
// @Contact wangkun_lc@inspur.com
package routers

import (
	"github.com/inspursoft/board/src/apiserver/controllers/auths"
	"github.com/inspursoft/board/src/apiserver/controllers/configmaps"
	"github.com/inspursoft/board/src/apiserver/controllers/dashboards"
	"github.com/inspursoft/board/src/apiserver/controllers/emails"
	"github.com/inspursoft/board/src/apiserver/controllers/helms/releases"
	"github.com/inspursoft/board/src/apiserver/controllers/helms/repositories"
	"github.com/inspursoft/board/src/apiserver/controllers/images"
	"github.com/inspursoft/board/src/apiserver/controllers/images/registries"
	"github.com/inspursoft/board/src/apiserver/controllers/jenkinsjobs"
	"github.com/inspursoft/board/src/apiserver/controllers/jobs"
	"github.com/inspursoft/board/src/apiserver/controllers/nodegroups"
	"github.com/inspursoft/board/src/apiserver/controllers/nodegroups/nodes"
	"github.com/inspursoft/board/src/apiserver/controllers/operations"
	"github.com/inspursoft/board/src/apiserver/controllers/persistences"
	"github.com/inspursoft/board/src/apiserver/controllers/persistences/claims"
	"github.com/inspursoft/board/src/apiserver/controllers/projects"
	"github.com/inspursoft/board/src/apiserver/controllers/projects/members"
	"github.com/inspursoft/board/src/apiserver/controllers/searches"
	"github.com/inspursoft/board/src/apiserver/controllers/services"
	"github.com/inspursoft/board/src/apiserver/controllers/services/autoscales"
	"github.com/inspursoft/board/src/apiserver/controllers/services/deployments"
	"github.com/inspursoft/board/src/apiserver/controllers/services/rollingupdates"
	"github.com/inspursoft/board/src/apiserver/controllers/services/scales"
	"github.com/inspursoft/board/src/apiserver/controllers/services/sessions"
	"github.com/inspursoft/board/src/apiserver/controllers/services/statefulsets"
	"github.com/inspursoft/board/src/apiserver/controllers/services/steps"
	"github.com/inspursoft/board/src/apiserver/controllers/storages/nfs"
	"github.com/inspursoft/board/src/apiserver/controllers/systems"
	"github.com/inspursoft/board/src/apiserver/controllers/uploadfiles"
	"github.com/inspursoft/board/src/apiserver/controllers/users"
	"github.com/inspursoft/board/src/apiserver/controllers/users/admins"

	"github.com/astaxie/beego"
)

func InitRouterV2() {
	ns := beego.NewNamespace("/api/v2",
		beego.NSNamespace("/auths",
			beego.NSInclude(
				&auths.AuthController{},
			),
		),
		beego.NSNamespace("/auths/password",
			beego.NSInclude(
				&auths.PasswordController{},
			),
		),
		beego.NSNamespace("/users",
			beego.NSInclude(
				&users.CommonController{},
				&users.PasswordController{},
			),
		),
		beego.NSNamespace("/users/admins",
			beego.NSInclude(
				&admins.CommonController{},
			),
		),
		beego.NSNamespace("/users/admins/supplements",
			beego.NSInclude(
				&admins.SupplementController{},
			),
		),
		beego.NSNamespace("/users/probe",
			beego.NSInclude(
				&users.ProbeController{},
			),
		),
		beego.NSNamespace("/users/supplements",
			beego.NSInclude(
				&users.SupplementController{},
			),
		),
		beego.NSNamespace("/systems",
			beego.NSInclude(
				&systems.SupplementController{},
			),
		),
		beego.NSNamespace("/searches",
			beego.NSInclude(
				&searches.SearchController{},
			),
		),
		beego.NSNamespace("/projects",
			beego.NSInclude(
				&projects.CommonController{},
			),
		),
		beego.NSNamespace("/projects/supplements",
			beego.NSInclude(
				&projects.SupplementController{},
			),
		),
		beego.NSNamespace("/projects/members",
			beego.NSInclude(
				&members.CommonController{},
			),
		),
		beego.NSNamespace("/images/builds",
			beego.NSInclude(
				&images.BuildController{},
			),
		),
		beego.NSNamespace("/images/supplements",
			beego.NSInclude(
				&images.SupplementController{},
			),
		),
		beego.NSNamespace("/images/registries",
			beego.NSInclude(
				&registries.CommonController{},
			),
		),
		beego.NSNamespace("/persistences",
			beego.NSInclude(
				&persistences.CommonController{},
			),
		),
		beego.NSNamespace("/persistences/claims",
			beego.NSInclude(
				&claims.CommonController{},
			),
		),
		beego.NSNamespace("/configmaps",
			beego.NSInclude(
				&configmaps.CommonController{},
			),
		),
		beego.NSNamespace("/nodegroups",
			beego.NSInclude(
				&nodegroups.CommonController{},
			),
		),
		beego.NSNamespace("/nodegroups/supplements",
			beego.NSInclude(
				&nodegroups.SupplementController{},
			),
		),
		beego.NSNamespace("/nodes",
			beego.NSInclude(
				&nodes.CommonController{},
			),
		),
		beego.NSNamespace("/nodes/supplements",
			beego.NSInclude(
				&nodes.SupplementController{},
			),
		),
		beego.NSNamespace("/storages/nfs",
			beego.NSInclude(
				&nfs.CommonController{},
			),
		),
		beego.NSNamespace("/dashboards",
			beego.NSInclude(
				&dashboards.DataController{},
			),
		),
		beego.NSNamespace("/services",
			beego.NSInclude(
				&services.CommonController{},
			),
		),
		beego.NSNamespace("/services/supplements",
			beego.NSInclude(
				&services.SupplementController{},
			),
		),
		beego.NSNamespace("/services/rollingupdates",
			beego.NSInclude(
				&rollingupdates.ImageController{},
				&rollingupdates.NodeGroupController{},
			),
		),
		beego.NSNamespace("/services/sessions",
			beego.NSInclude(
				&sessions.CommonController{},
			),
		),
		beego.NSNamespace("/services/deployments",
			beego.NSInclude(
				&deployments.CommonController{},
			),
		),
		beego.NSNamespace("/services/statefulsets",
			beego.NSInclude(
				&statefulsets.CommonController{},
			),
		),
		beego.NSNamespace("/services/scales",
			beego.NSInclude(
				&scales.CommonController{},
			),
		),
		beego.NSNamespace("/services/autoscales",
			beego.NSInclude(
				&autoscales.CommonController{},
			),
		),
		beego.NSNamespace("/services/steps",
			beego.NSInclude(
				&steps.CommonController{},
			),
		),
		beego.NSNamespace("/uploadfiles",
			beego.NSInclude(
				&uploadfiles.CommonController{},
			),
		),
		beego.NSNamespace("/jenkinsjobs",
			beego.NSInclude(
				&jenkinsjobs.SupplementController{},
			),
		),
		beego.NSNamespace("/emails",
			beego.NSInclude(
				&emails.SupplementController{},
			),
		),
		beego.NSNamespace("/operations",
			beego.NSInclude(
				&operations.CommonController{},
			),
		),
		beego.NSNamespace("/helms/repositories",
			beego.NSInclude(
				&repositories.CommonController{},
			),
		),
		beego.NSNamespace("/helms/releases",
			beego.NSInclude(
				&releases.CommonController{},
			),
		),
		beego.NSNamespace("/jobs",
			beego.NSInclude(
				&jobs.CommonController{},
			),
		),
		beego.NSNamespace("/jobs/supplements",
			beego.NSInclude(
				&jobs.SupplementController{},
			),
		),
	)
	beego.AddNamespace(ns)
}
