apiVersion: v1
appVersion: 3.0.4
deprecated: true
description: A Fluentd Helm chart for Kubernetes with Elasticsearch output
engine: gotpl
home: https://www.fluentd.org/
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
keywords:
- fluentd
- elasticsearch
- multiline
- detect-exceptions
- logging
name: native-fluentd-elasticsearch
sources:
- https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch
- https://github.com/fluent/fluentd-kubernetes-daemonset
- https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions
- https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image
version: 9.6.2
